name: Streamlit App Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check app structure
      run: |
        python -c "
        import os
        required_files = ['app.py', 'requirements.txt', 'config.py']
        missing = [f for f in required_files if not os.path.exists(f)]
        if missing:
            print(f'Missing required files: {missing}')
            exit(1)
        print('All required files present')
        "
    
    - name: Verify no secrets in code
      run: |
        if grep -r "sk-" . --exclude-dir=.git --exclude="*.md" --exclude="deploy_to_github.py"; then
          echo "Potential API keys found in code!"
          exit 1
        fi
        echo "No API keys detected in code"
